drop table Subscribers;
drop table Request;
drop table Message;
drop table Rate;
drop table Comment;
drop table Post cascade;
drop table Rater cascade;




create table Rater(
	rater_id int generated by default as identity primary key,
	nickname varchar(45) not null unique,
	password varchar (40) not null,
	telephone varchar(16) not null unique,
	enabled boolean not null,
	faceimage varchar(128) not null,
	bodyimage varchar(128) not null,
	total_rate double precision,
	score double precision not null,
	gender smallint  not null,
	role varchar(12) not null,
	status smallint not null,
	theme smallint not null,
	notification boolean not null,
	language smallint not null
);

create table Subscribers(
	rater_id int references Rater(rater_id),
	subscriber_id int references Rater(rater_id),
	primary key (rater_id, subscriber_id)
);


create table Request(
	request_id int generated by default as identity primary key,
	datetime timestamp not null,
	request_from_id int references Rater(rater_id),
	request_to_id int references Rater(rater_id)
);

create table Message(
	message_id int generated by default as identity primary key,
	datetime timestamp not null,
	message_content varchar(1000) not null,
	message_from_id int references Rater(rater_id),
	message_to_id int references Rater(rater_id)
);

create table Post(
	post_id int generated by default as identity primary key,
	datetime timestamp not null,
    post_content varchar(1000) not null,
    fire int,
	shit int,
	writer int references Rater(rater_id) not null
);

create table Rate(
	rate_id int generated by default as identity primary key,
	datetime timestamp not null,
	rate_value numeric(4,2),
	rate_from_id int references Rater(rater_id),
	rate_to_id int references Rater(rater_id)
);


create table Comment(
	comment_id int generated by default as identity primary key,
	datetime timestamp not null,
	comment_content varchar(150) not null,
	fire int,
	shit int,
	author int references Rater(rater_id),
	post_identificator int references Post(post_id)
	
);

insert into Rater (nickname, password, telephone, enabled, faceimage, bodyimage, total_rate, score, gender, role, status, theme, notification, language) values('Bogdan','passwordb','+380975420711', true, 'faceimage', 'bodyaimage', 123.45, 654.32, 1, 'USER', 0, 1, true, 1);
select * from Rater;


